linters-settings:
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 3
  gocyclo:
    max-complexity: 20
  gci:
    sections:
      - standard                       # Captures all standard packages if they do not match another section.
      - default                        # Contains all imports that could not be matched to another section type.
      - prefix(github.com/ognick/word_of_wisdom) # Groups all imports with the specified Prefix.
    custom-order: true
    skip-generated: false
    no-inline-comments: false
    no-prefix-comments: false
  lll:
    line-length: 140
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped

linters:
  disable-all: true
  enable:
    - lll
    - gofmt
    - goimports
    - whitespace
    - gocyclo
    - gci

# don't enable:
#    - wsl
#    - bodyclose
#    - deadcode
#    - depguard
#    - dogsled
#    - dupl
#    - errcheck
#    - exportloopref
#    - funlen
#    - gochecknoinits
#    - gocritic
#    - gocyclo
#    - gomnd
#    - goprintffuncname
#    - gosec
#    - gosimple
#    - govet
#    - ineffassign
#    - misspell
#    - nakedret
#    - noctx
#    - nolintlint
#    - staticcheck
#    - structcheck
#    - stylecheck
#    - typecheck
#    - unconvert
#    - unparam
#    - unused
#    - varcheck
#    - asciicheck
#    - scopelint
#    - gochecknoglobals
#    - gocognit
#    - godot
#    - godox
#    - goerr113
#    - interfacer
#    - maligned
#    - nestif
#    - prealloc
#    - testpackage
#    - revive