// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"fmt"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/ognick/word_of_wisdom/internal/common/config"
	config2 "github.com/ognick/word_of_wisdom/internal/server/internal/config"
	"github.com/ognick/word_of_wisdom/internal/server/internal/services/challenge"
	challenge2 "github.com/ognick/word_of_wisdom/internal/server/internal/services/challenge/usecase"
	"github.com/ognick/word_of_wisdom/internal/server/internal/services/wisdom"
	v1_2 "github.com/ognick/word_of_wisdom/internal/server/internal/services/wisdom/api/http/v1"
	"github.com/ognick/word_of_wisdom/internal/server/internal/services/wisdom/api/tcp/v1"
	http2 "github.com/ognick/word_of_wisdom/pkg/http"
	"github.com/ognick/word_of_wisdom/pkg/logger"
	"github.com/ognick/word_of_wisdom/pkg/pow"
	"github.com/ognick/word_of_wisdom/pkg/tcp"
	"net"
	"net/http"
)

// Injectors from init.go:

func InitializeApp() (*App, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	logger, err := provideLogger(configConfig)
	if err != nil {
		return nil, err
	}
	config3, err := config2.NewConfig()
	if err != nil {
		return nil, err
	}
	proofOfWorkGenerator := provideProofOfWorkGenerator(config3)
	usecasesChallenge := challenge.ProvideUsecase(proofOfWorkGenerator)
	repositoriesWisdom := wisdom.ProvideRepo()
	usecasesWisdom := wisdom.ProvideUsecase(repositoriesWisdom)
	challengeTimeout := provideChallengeTimeout(configConfig)
	handler := v1.NewHandler(usecasesChallenge, usecasesWisdom, challengeTimeout)
	v := v1.ProvideTCPHandle(handler)
	server := provideTCPServer(configConfig, v)
	v1Handler := v1_2.NewHandler(usecasesChallenge, usecasesWisdom)
	engine := initHTTPRouter(v1Handler)
	httpHandler := provideHTTPHandler(engine)
	httpServer := provideHTTPServer(configConfig, httpHandler)
	app := NewApp(logger, server, httpServer)
	return app, nil
}

// init.go:

func provideLogger(cfg config.Config) (logger.Logger, error) {
	l := logger.NewLogger()
	if err := logger.SetLogLevel(cfg.LogLevel); err != nil {
		return l, fmt.Errorf("failed set log level: %v", err)
	}
	return l, nil
}

func provideChallengeTimeout(cfg config.Config) v1.ChallengeTimeout {
	return v1.ChallengeTimeout(cfg.ChallengeTimeout)
}

func provideProofOfWorkGenerator(cfg config2.Config) challenge2.ProofOfWorkGenerator {
	return pow.NewGenerator(cfg.ChallengeComplexity)
}

func provideTCPServer(cfg config.Config, handler func(conn net.Conn)) *tcp.Server {
	return tcp.NewServer(cfg.TCPAddress, handler)
}

func provideHTTPServer(cfg config.Config, handler http.Handler) *http2.Server {
	return http2.NewServer(cfg.HTTPAddress, handler)
}

func provideHTTPHandler(router *gin.Engine) http.Handler {
	return router
}

var Application = wire.NewSet(
	NewApp, config.NewConfig, config2.NewConfig, provideLogger, wisdom.Init, challenge.Init, provideChallengeTimeout,
	provideProofOfWorkGenerator,

	provideTCPServer,

	provideHTTPServer,
	initHTTPRouter,
	provideHTTPHandler,
)
