// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"fmt"
	"github.com/google/wire"
	"github.com/ognick/word_of_wisdom/internal/common/config"
	config2 "github.com/ognick/word_of_wisdom/internal/server/internal/config"
	"github.com/ognick/word_of_wisdom/internal/server/internal/services/challenge"
	challenge2 "github.com/ognick/word_of_wisdom/internal/server/internal/services/challenge/usecase"
	"github.com/ognick/word_of_wisdom/internal/server/internal/services/wisdom"
	v1_2 "github.com/ognick/word_of_wisdom/internal/server/internal/services/wisdom/api/http/v1"
	"github.com/ognick/word_of_wisdom/internal/server/internal/services/wisdom/api/tcp/v1"
	"github.com/ognick/word_of_wisdom/pkg/http"
	"github.com/ognick/word_of_wisdom/pkg/logger"
	"github.com/ognick/word_of_wisdom/pkg/pow"
	"github.com/ognick/word_of_wisdom/pkg/tcp"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	logger, err := provideLogger(configConfig)
	if err != nil {
		return nil, err
	}
	address := provideTCPAddress(configConfig)
	config3, err := config2.NewConfig()
	if err != nil {
		return nil, err
	}
	complexity := provideChallengeComplexity(config3)
	proofOfWorkGenerator := provideProofOfWorkGenerator(complexity)
	usecasesChallenge := challenge.ProvideUsecase(proofOfWorkGenerator)
	repositoriesWisdom := wisdom.ProvideRepo()
	usecasesWisdom := wisdom.ProvideUsecase(repositoriesWisdom)
	challengeTimeout := provideChallengeTimeout(configConfig)
	handler := v1.NewHandler(usecasesChallenge, usecasesWisdom, challengeTimeout)
	v := v1.ProvideTCPHandle(handler)
	server := tcp.NewServer(address, v)
	httpAddress := provideHTTPAddr(configConfig)
	v1Handler := v1_2.NewHandler(usecasesChallenge, usecasesWisdom)
	httpHandler := v1_2.ProvideHTTPEngine(v1Handler)
	httpServer := http.NewServer(httpAddress, httpHandler)
	app := NewApp(logger, server, httpServer)
	return app, nil
}

// wire.go:

func provideLogger(cfg config.Config) (logger.Logger, error) {
	l := logger.NewLogger()
	if err := logger.SetLogLevel(cfg.LogLevel); err != nil {
		return l, fmt.Errorf("failed set log level: %v", err)
	}
	return l, nil
}

func provideChallengeComplexity(cfg config2.Config) pow.Complexity {
	return cfg.ChallengeComplexity
}

func provideChallengeTimeout(cfg config.Config) v1.ChallengeTimeout {
	return v1.ChallengeTimeout(cfg.ChallengeTimeout)
}

func provideProofOfWorkGenerator(complexity pow.Complexity) challenge2.ProofOfWorkGenerator {
	return pow.NewGenerator(complexity)
}

func provideTCPAddress(cfg config.Config) tcp.Address {
	return tcp.Address(cfg.TCPAddress)
}

func provideHTTPAddr(cfg config.Config) http.Address {
	return http.Address(cfg.HTTPAddress)
}

var Application = wire.NewSet(
	NewApp,

	provideLogger, config.Set, config2.Set, wisdom.Set, challenge.Set, provideChallengeComplexity,
	provideChallengeTimeout,
	provideProofOfWorkGenerator, tcp.NewServer, provideTCPAddress, http.NewServer, provideHTTPAddr,
)
