// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/": {
            "get": {
                "description": "Middleware to protect endpoints with Proof-of-Work.\nClients must solve a server-provided challenge and submit the solution in the header.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ProofOfWork"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Header containing the generated challenge (provided only on the first request).",
                        "name": "X-Challenge",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Header containing the solution to the challenge for validation (for subsequent requests).",
                        "name": "X-Solution",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Validation passed successfully."
                    },
                    "401": {
                        "description": "Invalid challenge solution."
                    },
                    "500": {
                        "description": "Failed to generate a challenge."
                    }
                }
            }
        },
        "/wisdom": {
            "get": {
                "description": "Get wisdom",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wisdom"
                ],
                "summary": "Get wisdom",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Wisdom"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.Wisdom": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
