definitions:
  dto.Wisdom:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/wisdom:
    get:
      consumes:
      - application/json
      description: Get wisdom
      parameters:
      - description: Header containing the generated challenge (provided only on the
          first request).
        in: header
        name: X-Challenge
        type: string
      - description: Header containing the solution to the challenge for validation
          (for subsequent requests).
        in: header
        name: X-Solution
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Wisdom'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get wisdom
      tags:
      - V1
swagger: "2.0"
